// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MusicaAut_GaldonMario.Models
{
    [Table("Artist")]
    public partial class Artist
    {
        public Artist()
        {
            Albums = new HashSet<Album>();
        }

        [Key]
        [DisplayName("Artista")]
        public int ArtistId { get; set; }
        [StringLength(120)]
        [MaxLength(16,ErrorMessage ="El maximo de caracteres es 16")]
        [MinLength(3,ErrorMessage ="EL minimo de caracteres es 3 ")]
        [DisplayName("Nombre")]
        public string Name { get; set; }

        [InverseProperty("Artist")]
        public virtual ICollection<Album> Albums { get; set; }
    }
}